version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=library
      - POSTGRES_USER=library
      - POSTGRES_DB=library
    volumes:
      - library-volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  library-volume: